version: '3'

services:

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    links:
      - db
      - mailcatcher:mail
    volumes:
      - ./src:/var/www/html:z
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    environment:
      SSH_AUTH_SOCK: /ssh-agent

  web:
      image: nginx:1.15
      volumes:
        - ./src:/var/www/html:z
        - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      links:
        - app
      ports:
        - "${WEB_PORT}:80"
      expose:
        - 80

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
    ports:
      - "${DB_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./docker/phpmyadmin/config.inc.php:/usr/share/nginx/html/config.inc.php:ro
    links:
      - db
    ports:
      - "${PHPMYADMIN_PORT}:80"

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "${MAILCATCHER_PORT}:80"

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    working_dir: /home/node/app
    command: tail -f /dev/null
    links:
      - app
    volumes:
      - ./src:/home/node/app
      - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    environment:
      SSH_AUTH_SOCK: /ssh-agent

  selenium:
    image: selenium/standalone-chrome
    links:
      - web
      - app

volumes:
  dbdata: